import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";
import { HomeItems, GetHomeData } from "../constant";
import Banners from '../components/Banners'
import Ribbons from '../components/Ribbons'

const Home: NextPage<{ banners: HomeItems,ribbons: HomeItems  }> = ({ banners , ribbons}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banners banners={banners} />
      <Ribbons ribbons={ribbons} />
    </div>
  );
};

export const getServerSideProps: GetStaticProps = async () => {

  const res = await fetch("https://apicdn.stag.vimai.io/tenants/odv/tenant_pages/home-page/ribbons/");
  const data: GetHomeData = await res.json();

  return {
    props: {
      banners: data?.banners,
      ribbons: data?.ribbons,
    },
  };
};

export default Home;