import Head from "next/head"
import HomePage from '@layouts/homepage'
import Layout from '@components/Layout'
import type { GetServerSideProps, InferGetServerSidePropsType } from "next";
import {
  useSetRecoilState,
} from 'recoil';
import { menuState } from "@provides/recoilState";
import { useEffect } from "react";
import * as types from "@constants/index"

function Home({ listMenu }: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const setListMenu = useSetRecoilState(menuState);
  useEffect(() => {
    setListMenu(() => listMenu);
  }, [listMenu])

  return (
    <>
      <Head>
        <title>Morning </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout >
        <HomePage />
      </Layout>
    </>
  );
};


export const getServerSideProps: GetServerSideProps<{
  listMenu:  any
}> = (async () => {
  const res = await fetch("https://65a8d1cb219bfa371867b0c1.mockapi.io/api/v1/menus");
  const listMenu = await res.json()
  return {
    props: {
      listMenu
    },
  };
  })

export default Home;
